targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            'lib/{{}}.dart': 'lib/_generated/{{}}.g.dart'
      freezed:
        options:
          build_extensions:
            'lib/{{}}.dart': 'lib/_generated/{{}}.freezed.dart'
      json_serializable:
        options:
          any_map: false
          checked: false
          constructor: ""
          create_factory: true
          create_field_map: false
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: pascal
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true
