name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.3.2
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.1
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.4.0
  http: ^1.1.0
  json_serializable: ^6.7.1
  logging: ^1.2.0
  retrofit: ^4.0.1
  url_strategy: ^0.2.0
  uuid: ^4.0.0

dev_dependencies:
  build_runner: ^2.4.6
  device_preview: ^1.1.0
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  retrofit_generator: ^7.0.8
  source_gen: ^1.4.0

flutter:
  uses-material-design: true
